name: build

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get semantic-release version
        shell: sh
        id: semantic-release-version
        run: "echo version=$(npm view @cihelper/semanticrelease-preset-generic dependencies.semantic-release) >> $GITHUB_OUTPUT"
      - name: Run semantic-release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          semantic_version: ${{ steps.semantic-release-version.outputs.version }}
          extra_plugins: "@cihelper/semanticrelease-preset-generic@1"
          extends: "@cihelper/semanticrelease-preset-generic"
