name: build

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup dependencies
        run: npm i --no-save @cihelper/preset-semanticrelease-githubaction
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --extends @cihelper/preset-semanticrelease-githubaction
      # https://github.com/marketplace/actions/actions-tagger
